### ISSUE TITLE
We used an Old Crunchy logo - must replace

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#25]
New ones have been emailed to Guido and Daniel.

**Comment by eddiepickle** [comment]
[
![StackedCircleLogo-01 (1)](https://user-images.githubusercontent.com/3721573/82220459-a9669e80-98ec-11ea-991b-5b2aee4dfcf5.png)
![CircleLogo_Color-01 (2)](https://user-images.githubusercontent.com/3721573/82220477-b1bed980-98ec-11ea-9791-1ed09dc6e06e.png)

](url)

**Comment by GuidoS** [comment]
fixed
