### ISSUE TITLE
Program Update:  Add in The Opportunity Project as the 1:05 Ignite

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#37]
In the 1:05 Ignite Slot

Dominica Zhu 
Director of Strategic Impact and Program Management , Census Open Innovation Labs 
U.S. Census Bureau  |  Department of Commerce
"The Opportunity Project:  Tackling Public-Facing Challenges Using Federal Open Data"

**Comment by GuidoS** [comment]
done
