### ISSUE TITLE
Input this data for Cesium's training session on Day 2

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#41]
Here are the Day 2 Training Sessions - to be delivered by Omar Shehata and Brady Moore:

Session 1: Make Your Data Work in Cesium (1 Hour) 
1. Bringing Data Into and Out of Cesium
2. Merging terrain data with Cesium World Terrain
3. Setup and Share a Cesium Story (bonus access to Vricon Surface Mesh for .gov or .mil users)

Session 2: Cesium Best Practices: How to Run Cesium on a Closed Network, or Fully Disconnected (1 Hour)

**Comment by GuidoS** [comment]
added the first session, but need a description for the second one.

**Comment by DanielJDufour** [comment]
Need to determine time
