### ISSUE TITLE
Put CosmiQ into the first (10:45) Lightning slot

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#43]
Title:
SpaceNet: Accelerating Open Source Analytic Techniques Through Partnerships
By: In-Q-Tel CosmiQ Works

Summary:
Since its founding in 2016, the goal of SpaceNet has been to accelerate the development and dissemination of open source, machine learning techniques for geospatial applications, specifically foundational mapping. The organization has achieved this through four pillars: (1) publishing labeled datasets; (2) structuring and hosting public data science challenges; (3) open sourcing leading machine learning models; and (4) conducting rigorous evaluation of the datasets and models. Commercial, nonprofit, and government organizations have joined as SpaceNet Partners over the years in an effort to help expand the depth, breath, and reach of these pillars. In this lightning talk, SpaceNet leadership briefly describe the history of organization, progress made to date, and the roadmap for the coming year.

**Comment by GuidoS** [comment]
resolved
