### ISSUE TITLE
Invoice Prominent Edge as Silver Sponsor

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#45]
Syrus Mesdaghi   
CEO, Prominent Edge
O: 866-225-5731 x700M: 571-232-6292
syrusm@prominentedge.com
[FedGeoDay Sponsorship Form 20200519a (1).pdf](https://github.com/OSGeo-US/fedgeoday.us/files/4703531/FedGeoDay.Sponsorship.Form.20200519a.1.pdf)

**Comment by GuidoS** [comment]
resolved
