### ISSUE TITLE
Add Element84 / Matt Hanson Training Session to the agenda for Friday

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#47]
Title "Using STAC and Open-Source Tools with Sentinel-2 data"

Here's the description of our proposed session by Matt Hanson of Element84 and Vincent Sarago of DevelopmentSeed 

"Sentinel-2 atmospherically corrected (Level 2) data was recently generated for all of Africa and going back at least 3 years for the Digital Earth Africa project. However, this data has been stored in a Requester Pays bucket on AWS S3 in JPEG2K format which has limited some uses. Element 84 is working with Geoscience Australia to convert this data to Cloud-Optimized GeoTIFF, generating metadata in the new SpatioTemporal Asset Catalog (STAC). The data itself is free and open to anyone, and is easily discoverable via the STAC API.
In this short tutorial we will look at the STAC metadata, the format of the data files themselves, and will demonstrate how to use some Open-source tools such as sat-search to query the STAC API and find data of interest. We will also discuss the ecosystem of Open-Source tools that can be used with STAC for downloading raw files, reading windows of the data directly, and tiling scenes dynamically via Lambda functions."

Let me know what you think.  How many minutes presenting would we plan for?
Best,
Ariel

**Comment by GuidoS** [comment]
Need to know which time slot to put this into,

**Comment by DanielJDufour** [comment]
1-4pm. I'll add this in today

**Comment by DanielJDufour** [comment]
done
