### ISSUE TITLE
Change Titles for The Opportunity Project Day 1 Lightning &  Day 2 Training

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#51]
Change Day 1 lightning talk title to:  "The Opportunity Project: Earth Sprints"

Change Day 2 Workshop to:  "Solving Environmental Challenges with Open Data and Human-Centered Design"

For Day 2 training add these trainers:
Haley Ashcom, Strategic Liaison, Census Open Innovation Labs 
Emma Brennan,  Designer, Census Open Innovation Labs 
Dominica Zhu, Director of Strategic Impact and Program Management, Census Open Innovation Labs

**Comment by DanielJDufour** [comment]
I'll do this

**Comment by DanielJDufour** [comment]
done
