### ISSUE TITLE
Input this timing on the website for the Crunchy Data Day 2 Sessions

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#53]
all times Eastern)
9:00-12:00 - Introductions to PostGIS
1:00-2:30 - pg_tileserv and pg_featureserv
2:45-4:00 - AMA with Paul Ramsey

**Comment by GuidoS** [comment]
ok, this combining the tickets. It's one session in the afternoon.

I will leave this open until the Eventbrite side of this is resolved.
