### ISSUE TITLE
Replace "Details" under Keynote speaker with bio listed below 

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#68]
@DanielJDufour  Take out the "Details" under Chelle's picture and replace with this bio:

Chelle is a passionate advocate for open science, open source software, and inclusivity.  Chelle co-chaired the National Academies’ Report on Open Source Software Policy Options for NASA Earth and Space Sciences, and in addition to being a full time oceanographer, also works with NASA on teaching open source and science best practices to researchers through the Openscapes project: https://www.openscapes.org/. As a physical oceanographer focused on remote sensing, she has worked for over 25 years on retrievals of ocean temperature from space and using that data to understand how the ocean impacts our lives.  Her more recent research focuses on interdisciplinary science using cloud computing, open source software algorithm development, air-sea fluxes, biophysical interactions, and upper ocean physical processes.  She has served on scientific committees, notably as co-chair of a standing committee for the National Academy of Sciences and has presented to a federal house committee on NASA's implementation of scientific community priorities.

**Comment by DanielJDufour** [comment]
done
