### ISSUE TITLE
Slightly edited bio on Chelle Gentemann

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#69]
@DanielJDufour - Chelle edited the bio I had put together.  Can you swap this text in:

Chelle is a passionate advocate for open science, open source software, and inclusivity.  She co-chaired the National Academies’ Report on Open Source Software Policy Options for NASA Earth and Space Sciences, and in addition to being a full time oceanographer, also leads the development of open source and open science best practices for NASA researchers. As a physical oceanographer focused on remote sensing, she has worked for over 25 years on retrievals of ocean temperature from space and using that data to understand how the ocean impacts our lives. She is the lead scientist on a proposed new NASA satellite, Butterfly. Her more recent research focuses on using cloud computing for interdisciplinary science, air-sea interaction research, and geophysical algorithm development. She has served on scientific committees, notably as co-chair of a standing committee for the National Academy of Sciences, and has presented to a federal house committee on NASA's implementation of scientific community priorities.

**Comment by DanielJDufour** [comment]
@eddiepickle , please see my recent email.
