### ISSUE TITLE
Add Program Content Overview to the Website

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#70]
@DanielJDufour   

Looks like Guido input program info on the website.  However, the text is small and the formatting is not good.  Can you fix that to look more like below?  Also, increase the size of the program info and reduce the size of the Team info?

Eddie

https://docs.google.com/document/d/1kn1NsOtNBupVkJnYaCwHf_p6dKyTo7zbatmAoKC_jBQ/edit?usp=sharing

**Program Sessions:**

- June 8 "Program Day" includes plenary presentations, panel discussions, and lightning talks by leading experts.

- June 9 “Hands On Day”  includes an extensive set of training opportunities on leading open source technologies. Hands on Day will require registration for specific sessions and sessions may have a minimal fee.

 
**Program Day Sessions:**

- Federal Agencies Innovating Through OpenStreetMap

- Executive Roundtable:  Building Federal Programs Through Open Ecosystems

- Assuring Federal Program Software Supply Chains Using OSS

- Open Source Geospatial Software & Federal Programs (Two Sessions)
   - Finding FOSS4G Solutions for Building Federal Programs
   - Programs Creating Open Source Software:  “Sharing the Geospatial Love Through FOSS Development”

- Machine Learning & Open Ecosystems (Three Sessions)
   - Human-in-the-Loop Active Learning AI
   - Open, Standardized Data and Methodologies for Open Science
   - Open Ecosystems for AI/ML-Based Object Detection

- Applying Open Innovation Culture and Effective Models within Federal Agencies to Tackle Geospatial Challenges

- Lightning Talks and Networking

**Comment by GuidoS** [comment]
issues have been addressed
