### ISSUE TITLE
Add two new Silver Sponsor logos to website

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#81]
@DanielJDufour We have added Silver sponsors Critigen and Confluent.  The Critigen logos are attached but I'll email the Confluent one.

![CRITIGEN-green](https://user-images.githubusercontent.com/3721573/117876822-cde02700-b271-11eb-99cf-b4d7c39c2be8.png)
![CRITIGEN-green_box](https://user-images.githubusercontent.com/3721573/117876826-cde02700-b271-11eb-9fac-969bce62c988.png)

**Comment by DanielJDufour** [comment]
done
