### ISSUE TITLE
Change program on website

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#82]
@DanielJDufour @guidostein This may be OBE if you just go ahead and put up the program grid, but we need to change the program from:

Machine Learning & Open Ecosystems (Three Sessions)
- Human-in-the-Loop Active Learning AI
- Open, Standardized Data and Methodologies for Federal AI/ML Programs
- Open Ecosystems for AI/ML-Based Object Detection

to:

Machine Learning & Open Ecosystems (Two Sessions)
- Human-in-the-Loop Active Learning AI
- Open, Standardized Data and Methodologies for Federal AI/ML Programs

**Comment by DanielJDufour** [comment]
obe
