### ISSUE TITLE
Website change needed

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#87]
@DanielJDufour 

We need to change the listing for 

- "Federal Agencies Innovating Through OpenStreetMap"
To:
"Partnering for Innovation: A Collaboration between Federal Agencies and OSMUS"

Also, we need to add another panelist
- Leslie Haig, US DOT

So, the complete panelist list is:

Greg Matthews, USGS
Derald Dudley, US DOT
Jim McAndrew, NPS
Leslie Haig, US DOT
Maggie Cawley, OSM US

**Comment by DanielJDufour** [comment]
done
