### ISSUE TITLE
Put Chitra Sivanandam and David Carter on Website

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#88]
@DanielJDufour 

linkedin.com/in/david-carter-902a321
![David Carter](https://user-images.githubusercontent.com/3721573/119891665-41876280-bf07-11eb-93e7-68b5a9d3721f.jpeg)

linkedin.com/in/chitra-sivanandam-073698

**Comment by eddiepickle** [comment]
![chitra_pic](https://user-images.githubusercontent.com/3721573/119903437-b44c0a00-bf16-11eb-98fa-2cebc8954708.png)

**Comment by eddiepickle** [comment]
David Carter
Geospatial Information Officer
U.S. Department of the Interior

Chitra Sivanandam
Chief Technology Officer
Reinventing Geospatial, Inc. (RGi)

**Comment by DanielJDufour** [comment]
done
