### ISSUE TITLE
Edits needed for the card for Finding FOSS4G Solutions for Building Federal Programs on the website

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#89]
@DanielJDufour 

Please make the following changes to the card for Finding FOSS4G Solutions for Building Federal Programs

- For moderator Luis Bermudez change to
- Luis Bermudez, CEO GeoSolutions USA

For panelists please change to this:

- Arwen De la Torre (NGA / OSM)
- Calvin Hamilton (NSA)
- Rich Frazier (FGDC) 
- Shayne Urbanowski (USGS)
- Monica Mardel (CENSUS/GEO FED)

**Comment by eddiepickle** [comment]
@DanielJDufour 

Also for the 12:15 panel on June 8, can you change the moderator's title to:
Tackling Geospatial Challenges Through Open Innovation Models within Federal Agencies
Moderator:  Anna Valuev
**Head of Strategic Initiatives**, The Opportunity Project (TOP)
Census Open Innovation Labs
U.S. Census Bureau

**Comment by DanielJDufour** [comment]
Hi, @eddiepickle and @GuidoS .  I saw that some of this work was done.  Is this work complete?  Can this issue be closed?

**Comment by GuidoS** [comment]
Yeah, I was just fixing things left and right earlier today.

Feel free to close issues as you see fit.

-Guido
