### ISSUE TITLE
Correction needed on Website for June 9 "User Research Methods: Paper Prototyping Workshop" 

### ISSUE THREAD

**Issue by eddiepickle** [OSGeo-US/fedgeoday.us#91]
@DanielJDufour  The moderator for the session should be Emma Brennan.

Please remove "Bolt Brennan"

Thanks!

**Comment by eddiepickle** [comment]
Change -- we need to cancel this session.  Can we remove it from the website?

**Comment by DanielJDufour** [comment]
I'll remove it now.

**Comment by DanielJDufour** [comment]
done
